### ISSUE TITLE
expected release for wasm support?

### ISSUE THREAD

**Issue by ImUrX** [Lokathor/wide#100]
when is 0.7 expected to be released? (i dont think it should be 0.6.6 if its gonna add a feature as big as wasm support)

**Comment by Lokathor** [comment]
Well, to answer the second part first: semver is about compatibility rather than bigness of new features.

second, the next release will be 0.7 because cryze adjusted how some of the operations work when we realized how inconsistent some parts of floating ops are.

I'll do it in a few minutes.

**Comment by Lokathor** [comment]
https://docs.rs/wide/0.7.0/wide/index.html

**Comment by ImUrX** [comment]
thanks a lot :D
