### ISSUE TITLE
``i64x2`` multiplication

### ISSUE THREAD

**Issue by ImUrX** [Lokathor/wide#102]
this is kind of wasm only (and it translates to [10 instructions](https://github.com/v8/v8/blob/b6520eda5eafc3b007a5641b37136dfc9d92f63d/src/compiler/backend/x64/code-generator-x64.cc#L2834-L2858)) but should this be implemented where possible?

**Comment by Lokathor** [comment]
I'd accept a PR that added that, but I'm not actively developing the crate much myself these days.

**Comment by ImUrX** [comment]
Already making it, is there a problem if i add support for operations with i64 that are splatted too?

**Comment by ImUrX** [comment]
alright, wish me luck
