### ISSUE TITLE
adding saturation arithmetic

### ISSUE THREAD

**Issue by mcroomp** [Lokathor/wide#122]
What do people think about adding saturating_add, sub, mul methods? Doesn't look like it would be too hard to add... there's intrinsics in safe_arch for this, and it would be useful in some signal processing scenarios that require sensible overflow handling. I can prepare a pull request if there isn't some reason that this wouldn't be a good idea.

The idea would be to just add them as methods, since the traits aren't stable.

**Comment by Lokathor** [comment]
Yeah we can generally accept new methods!

**Comment by mcroomp** [comment]
added #123

**Comment by mcroomp** [comment]
Done
