### ISSUE TITLE
MSRV vs aarch64

### ISSUE THREAD

**Issue by waywardmonkeys** [Lokathor/wide#169]
The MSRV is set to 1.56, but on aarch64 platforms, there's a clippy lint about the aarch64 code, like this:

```
warning: current MSRV (Minimum Supported Rust Version) is `1.56.0` but this item is stable since `1.59.0`
   --> src/u64x2_.rs:295:55
    |
295 |             unsafe {Self { neon: vshlq_u64(self.neon, vmovq_n_s64(-(rhs as i64))) }}
    |                                                       ^^^^^^^^^^^
...
308 | impl_shr_t_for_u64x2!(i8, u8, i16, u16, i32, u32, i64, u64, i128, u128);
    | ----------------------------------------------------------------------- in this macro invocation
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#incompatible_msrv
    = note: this warning originates in the macro `impl_shr_t_for_u64x2` (in Nightly builds, run with -Z macro-backtrace for more info)
```
It still compiles though!

**Comment by Lokathor** [comment]
Since 1.80 or so just came out, and since this is mostly used by gamedev sorts of folks who tend to have newest versions of the compiler, I think we can just bump the MSRV in an update.

**Comment by waywardmonkeys** [comment]
I can do a PR to increase it to 1.59 or 1.60.

`palette` has an optional dependency on this crate and has an MSRV of 1.60.

(I came to it via `simba` / `nalgebra` / `parry` / `rapier`.)

**Comment by Lokathor** [comment]
yeah, 1.60 is fine
