### ISSUE TITLE
Compile error on latest version (0.7.27)

### ISSUE THREAD

**Issue by pthurston** [Lokathor/wide#177]
Hello, 

It looks like there is a compile error on the latest version (0.7.27). 

Example Cargo.toml

> [package]
> name = "wide-compile-issue"
> version = "0.1.0"
> edition = "2021"
> 
> [dependencies]
> wide = {version="0.7.27"}

Example src/main.ts
> fn main() {
>     println!("Hello, world!");
> }

Output from `cargo run`

> Blocking waiting for file lock on build directory
>    Compiling bytemuck v1.16.3
>    Compiling safe_arch v0.7.2
>    Compiling wide v0.7.27
> error[E0425]: cannot find function `convert_to_i16_m128i_from_lower8_u8_m128i` in this scope
>    --> /Users/pthurston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wide-0.7.27/src/u16x16_.rs:243:27
>     |
> 243 |           a: u16x8 { sse: convert_to_i16_m128i_from_lower8_u8_m128i(v.sse) },
>     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `convert_to_i16_m128i_from_lower8_i8_m128i`
>     |
>    ::: /Users/pthurston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/safe_arch-0.7.2/src/x86_x64/sse4_1.rs:177:1
>     |
> 177 | pub fn convert_to_i16_m128i_from_lower8_i8_m128i(a: m128i) -> m128i {
>     | ------------------------------------------------------------------- similarly named function `convert_to_i16_m128i_from_lower8_i8_m128i` defined here
> 
> error[E0425]: cannot find function `convert_to_i16_m128i_from_lower8_u8_m128i` in this scope
>    --> /Users/pthurston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wide-0.7.27/src/u16x16_.rs:244:27
>     |
> 244 | ...u16x8 { sse: convert_to_i16_m128i_from_lower8_u8_m128i(unpack_high_i64_m128i...
>     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `convert_to_i16_m128i_from_lower8_i8_m128i`
>     |
>    ::: /Users/pthurston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/safe_arch-0.7.2/src/x86_x64/sse4_1.rs:177:1
>     |
> 177 | pub fn convert_to_i16_m128i_from_lower8_i8_m128i(a: m128i) -> m128i {
>     | ------------------------------------------------------------------- similarly named function `convert_to_i16_m128i_from_lower8_i8_m128i` defined here
> 
> For more information about this error, try `rustc --explain E0425`.
> error: could not compile `wide` (lib) due to 2 previous errors

**Comment by iam888** [comment]
mark it

**Comment by Lokathor** [comment]
dag how did that slip CI.

must be a typo in one of the cfg paths.

I'll yank the bad version in a moment and then try to figure it out a bit after that.

**Comment by Lokathor** [comment]
I believe that https://github.com/Lokathor/wide/pull/178 fixes things all up, and add a CI path for SSE4.1 to help prevent this popping up again. (The CI could be even more picky in the future, but for now I don't want to add more time to it really.)
