### ISSUE TITLE
 core::intrinsics::sqrtf32(x) Call to unsafe function

### ISSUE THREAD

**Issue by kettle11** [Lokathor/wide#22]
Line 138 in lib.rs needs to be changed to: 

`
unsafe { core::intrinsics::sqrtf32(x) }
`

Otherwise the build will fail on nightly for platforms without SSE support. I found this when I tried to build ultraviolet for Wasm.

**Comment by Lokathor** [comment]
Good catch. I'm upset that CI didn't notice that but it's because i only test stable for a lot of targets.

I've fixed that, and i'm letting the new CI run with an extra entry for nightly `wasm32-unknown-unknown`. Once that completes I'll publish a patch.

**Comment by Lokathor** [comment]
0.4.3 is out!
