### ISSUE TITLE
SSE4.1 truncate always slower than SSE2 truncate

### ISSUE THREAD

**Issue by mooman219** [Lokathor/wide#24]
I benched the SSE4.1 truncate with the SSE2 truncate and found the SSE4.1 version to be 5%-15% slower. Might not be worth keeping?
```rust
    pub fn trunc41(self) -> Self {
        unsafe { f32x4(_mm_round_ps(self.0, _MM_FROUND_TO_ZERO | _MM_FROUND_NO_EXC)) }
    }
```
```rust
    pub fn trunc2(self) -> Self {
        unsafe { f32x4(_mm_cvtepi32_ps(_mm_cvttps_epi32(self.0))) }
    }
```

**Comment by Lokathor** [comment]
This will give incorrect results for the weird float numbers: NAN, Inf, NegInf

**Comment by Lokathor** [comment]
I believe in 0.5 there's currently no truncate at all, though we do have rounding into an int type.

I'm gonna let this close.
