### ISSUE TITLE
Remove bytemuck dependency

### ISSUE THREAD

**Issue by mooman219** [Lokathor/wide#25]
It looks like the only tools from bytemuck being used are `cast, cast_mut, cast_ref, Pod, Zeroable` for a series of already known good casts (like `m128` -> `[f32; 4]`). This might be able to be removed for a raw transmute. This would marginally improve performance probably.

**Comment by Lokathor** [comment]
This is a performance concern.

`bytemuck` itself is actually under performing here. It's unwrapping the try_cast result, which inserts panic handling code that can't ever happen and llvm just doesn't quite see as being the case.

I'd like to tackle a fix at the bytemuck level first, which I think can be easily enough done with a compile time branch.

If we can't bring it up to full speed with a fix in bytemuck, we'll just use some bespoke transmutes. In this case, the Zeroable/Pod impls will remain as part of an optional bytemuck dependency.
