### ISSUE TITLE
f32x2?

### ISSUE THREAD

**Issue by RazrFalcon** [Lokathor/wide#32]
`pathfinder_simd` [implements](https://github.com/servo/pathfinder/blob/fed372229a4e4730b476be6436087d06f4f2ce0f/simd/src/x86/mod.rs#L30) it via `f32x4`. It's very useful when working with points/vectors.

**Comment by Lokathor** [comment]
Can't you use f32x4 and just ignore two of the lanes?

I'm not sure I see the benefit of having the f32x2 type, because the registers are 128-bit either way.

**Comment by RazrFalcon** [comment]
Sure, but it would be a handy wrapper, especially in a fallback mode (no sse2).

**Comment by Lokathor** [comment]
So the difficulty here is that f32x2 is a real SIMD type... that's only available with the Neon intrinsics set of ARM/Aarch64.

And then on Intel... there's no easy way to do it. People would sure expect that
```rust
size_of::<f32x2>() == size_of::<[f32;2>()
```
and if that's the case, then most operations using hardware would take a performance hit _per operation_ for moving the data into and out of SIMD mode.

I'm open to solutions if I haven't thought of something, but it feels like you should just use `f32x4` and ignore two lanes, or use `f64x2` if you really want only two lanes of data.

**Comment by RazrFalcon** [comment]
Can't you simply mimic pathfinder's behavior? Or is it flawed somehow?

Also, Skia works exactly the same: [SSE2](https://github.com/google/skia/blob/52a4379f03f7cd4e1c67eb69a756abc5838a658f/include/private/SkNx_sse.h#L38) and [NEON](https://github.com/google/skia/blob/52a4379f03f7cd4e1c67eb69a756abc5838a658f/include/private/SkNx_neon.h#L31). But they wrapped everything into a templates magic.

**Comment by Lokathor** [comment]
Well, so, basically storing 64 bits of float data in memory and then pushing it into a SIMD register with the high lanes as zeroed, and then doing one operation, and then pushing it back out to memory as a `u64`... that's going to have very bad performance almost all the time.

You'll get the correct numbers, but it's harsh on the CPU.

The correct way to use SIMD in a situation like this is generally to have a type like `Vec2x4` where you have 
```
pub struct Vec2x4 {
  x: f32x4,
  y: f32x4,
}
```
And then that one struct is four Vec2 values which you can process at once.

This is how [ultraviolet](https://docs.rs/ultraviolet) attains such high performance.

**Comment by RazrFalcon** [comment]
I haven't done any benchmarks yet, but Skia and pathfinder seams fine. And Skia is one of the fastest libraries out there (although,  the rendering itself doesn't use this type). I assume they did the benchmarks. 

I will try to benchmark it myself, but results on a single CPU will be a bit meaningless in this case.
