### ISSUE TITLE
exp and log/ln

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/wide#33]
* [x] exp
* [ ] log/ln

**Comment by ronniec95** [comment]
Hi can you please assign this to me. I've done the code changes for this but I can't seem to create a PR (error 403) for this repo.

exp() is done and I'd like to submit that for your review and then separately the ln/log functions

Thanks

**Comment by Lokathor** [comment]
I've assigned you, but I don't know why you can't submit a PR. I've never had that error before.

**Comment by Lokathor** [comment]
one down!

**Comment by ronniec95** [comment]
Close against #39
