### ISSUE TITLE
add more constants (matching 0.4.x at least?)

### ISSUE THREAD

**Issue by termhn** [Lokathor/wide#37]
for example ONE, ZERO, FRAC_PI_BLAH, etc.

**Comment by Lokathor** [comment]
one and zero I'm not sure we need constants for, those are easy enough to do.

fractions of tau I'm sure we can do

**Comment by termhn** [comment]
They are easy enough to do but I still use the constant versions throughout
my code cause I think it's convenient and makes semantically obvious what
you're using it for
