### ISSUE TITLE
move_mask for integer types

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/wide#38]
The only hardware move mask instruction is for `i8`, so it's unclear what we should do for the other integer types. They could just not support move mask at all, or we could try to... just have them give 16 bits of into even if they're less lanes wide? That's weird, but it is fast.

Something to think about I guess.

**Comment by tzcnt** [comment]
Any reason you implement i32x8::move_mask but not i8x32::move_mask? Since as you said, i8x32 is the one for which the instruction exists.

**Comment by Lokathor** [comment]
Separate people worked on those types and they each added mostly just what they needed for their own stuff to work. Should be fine enough to add more methods if someone wants to.

**Comment by mcroomp** [comment]
This is implemented now, can close the issue
