### ISSUE TITLE
Upgrade to avx instructions to double simd width f64x4, f32x8, u8x32 etc

### ISSUE THREAD

**Issue by ronniec95** [Lokathor/wide#46]
It would be nice to continue with stable releases and have access to safe_arch_*m256* functions

**Comment by Lokathor** [comment]
I'm open to the idea.

I want to see how the `packed_simd` discussion shakes out in the next few weeks. If they're serious about actually putting together a project to get into `core` then I think my SIMD time would be better served helping to push that forward.

On the other hand, if it goes back into dormancy then obviously the 256-but types in `wide` would be more important.

If anyone wants to PR this I'd be very open to it. Mostly it's just a lot of stuff that delegates to other existing functions based on various conditional compilation settings, so it should be pretty easy.

**Comment by ronniec95** [comment]
Assign it to me please. I'll take a look at it for now in my free time. But yeah, packed_simd is the right way forward

**Comment by Lokathor** [comment]
One possible design is to have a set of SimdAdd, SimdMul, etc traits, and then impl a lot of the more complex math functions in terms of those traits. Like how `generic_bit_blend` works

however, since we only have like 2 general SIMD widths to worry about (128-bit and 256-bit) that might not be worth the trouble to set up.

**Comment by termhn** [comment]
Hi @ronniec95 just wanted to ping and see if you had any update on this... no rush, I'm just curious to use it for my purposes in termhn/ultraviolet#50 :D

**Comment by termhn** [comment]
Oh hey I just saw #49 got merged, I guess this can be closed now :)
