### ISSUE TITLE
f32x8 type?

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/wide#5]

**Comment by dragostis** [comment]
What are your plans about adding more types from packed_simd apart from `f32x8`?

**Comment by Lokathor** [comment]
I would accept PRs, but I'm not personally working on this crate right now.

**Comment by Lokathor** [comment]
with version 0.5 out, we've got more types, but still only 128-bit types.

If people want to submit 256 bit types they can go in, but i'm still not personally interested in adding the 256-bit stuff at this time.
