### ISSUE TITLE
Use rustfmt

### ISSUE THREAD

**Issue by RazrFalcon** [Lokathor/wide#57]
I understand that this is a controversial question, but it's weird to see a Rust crate that doesn't follow Rust's code style, like basically everyone else.

Is there a chance you would switch to the default code style?

**Comment by Lokathor** [comment]
I do use rustfmt, as specified in the file included in the repo.

I am quite comfortable with 2-space indents. I use it in all my projects. I don't think I'm going to ever willingly switch away from 2-spaces.

**Comment by RazrFalcon** [comment]
Well, that was an attempt.
