### ISSUE TITLE
as_slice method

### ISSUE THREAD

**Issue by RazrFalcon** [Lokathor/wide#60]
Is there a method to get the wide type content as a slice of primitive types? Like `f32x4` -> `[f32; 4]`?

**Comment by Lokathor** [comment]
So far I've used `bytemuck` for this sort of thing when I need it.

If you want to add specific methods for it on various types I wouldn't be opposed to it.

**Comment by ronniec95** [comment]
What about an Index trait instead or as well?

**Comment by Lokathor** [comment]
I mean... it's all fine in the sense that it's technically possible for Rust to "just handle this" without the user having to think about it, but once you have a reference to a SIMD type it has to be pushed out of register to the stack (unless optimizations can totally remove the reference existing, which does happen sometimes).

So if we added Index and IndexMut to a type we'd probably want a note on the type to avoid them in hot code.

**Comment by RazrFalcon** [comment]
The Index trait will cause bound checking, too ineffective.

**Comment by Lokathor** [comment]
If you index by a const it is likely that the bound will be removed in optimization.
