### ISSUE TITLE
How do you test scalar implementations? 

### ISSUE THREAD

**Issue by RazrFalcon** [Lokathor/wide#61]
The create doesn't have dedicated SSE/AVX features and relies on `target_feature`, but it's [kinda broken](https://github.com/rust-lang/rust/issues/65844). How do you test the scalar implementations?

**Comment by Lokathor** [comment]
The i586 code paths are scalar paths. That's in CI.

Occasionally I also run the tests on my raspberry pi, which is aarch64.

Unfortunately there's no CI for automatic ARM/Aarch64 testing, but if you know how to do that please open a PR because I'd be happy to have such a thing.

**Comment by RazrFalcon** [comment]
I see. Thanks.
