### ISSUE TITLE
How to cast i32x4 to u32x4?

### ISSUE THREAD

**Issue by RazrFalcon** [Lokathor/wide#68]

**Comment by Lokathor** [comment]
Do you want value preserving or bit preserving?

for bit preserving, `bytemuck::cast` does it.

There's not currently anything that will like, convert and do something if the value was out of range.

**Comment by RazrFalcon** [comment]
Bit preserving. So I have to use `bytemuck` directly? 

Looks like the cast method uses panic. Does it guarantee that it will be optimized out for equal types? Otherwise it's too expensive for my use case.

**Comment by Lokathor** [comment]
yeah on equal types those checks all const fold away.

**Comment by RazrFalcon** [comment]
So for f32 to i32 I also have to use bytemuck and not `cast_to_m128i_from_m128d`/`_mm_castps_si128`?

**Comment by Lokathor** [comment]
yeah the core::arch bit preserving casts casts are just transmute internally
