### ISSUE TITLE
0.5.6 isn't semver compatible

### ISSUE THREAD

**Issue by Veykril** [Lokathor/wide#72]
Due to #62 `Moved cmp operators into traits. No usability changes.` which now requires one to import the trait to be able to use the functions which is a breaking change. Due to this [ultraviolet](https://crates.io/crates/ultraviolet) doesn't compile anymore for example.

This is ofc just assuming this crate intends to stay semver compatible in minor versions prior to a 1.0 release.

**Comment by Lokathor** [comment]
Ohhhhh gosh, i see. Right. Everyone using the crate in testing was glob importing, my bad.

I'll have to yank it and put it out as 0.6 later today.

**Comment by Lokathor** [comment]
Okay, 0.5.6 yanked and 0.6.0 released instead.
