### ISSUE TITLE
Should Debug include the type name?

### ISSUE THREAD

**Issue by RazrFalcon** [Lokathor/wide#75]
The `Debug` output for, let's say, `f32x4` looks like this:

```
(1.95763, 1.95276, 1.9478897, 1.9430195)
```

Maybe it would be better to have something like:

```
f32x4(1.95763, 1.95276, 1.9478897, 1.9430195)
```

**Comment by Lokathor** [comment]
possibly? f32 debug doesn't say it is an f32 though.

**Comment by RazrFalcon** [comment]
Yes, bu this is what `Debug` does by default. Also, `(1, 2, 3, 4)` can be either `i32x4` or `i64x4`. Hard to guess.

This is just a suggestion, by the way.

**Comment by Lokathor** [comment]
well a derived debug shows the type name of a structure sure, but debug on a f32 is still just the f32. that's also why it shows as 1 sometimes. Note that you can specify format arguments and each float within will respect that, so you can specify, i think it's `:0.0?` or something like that and it'll force the .0 part to print for whole numbers.
