### ISSUE TITLE
SSE2 support in i32x8/u32x8

### ISSUE THREAD

**Issue by RazrFalcon** [Lokathor/wide#76]
I'm trying to switch from f32x4 to f32x8 in my project, which is fairly straight-forward thanks to wide's fallback mechanism. But I also use a lot of i32x8/u32x8, which means that on SSE2 I'm stuck with scalar, which is very slow.

Is there a reason why i32x8/u32x8 doesn't support SSE2 fallback? `f32x8` also uses two `m128`, but requires only SSE2 and not SSSE3. 
I can try implementing SSE2 fallback for i32x8/u32x8 if you're interested.

**Comment by Lokathor** [comment]
No reason it just wasn't implemented that way. I'm open to a PR which does additional fallback cases of there's sse2 but no avx2
