### ISSUE TITLE
How to create i32x8 from two m128i?

### ISSUE THREAD

**Issue by RazrFalcon** [Lokathor/wide#77]
I wanted to add SSSE3 fallback to [f32x8::trunc_int](https://github.com/Lokathor/wide/blob/fb7c9d4ce0254fc990818b00041057dbb7400620/src/f32x8_.rs#L633), so I've naively wrote:

```rust
else if #[cfg(target_feature="ssse3")] {
    i32x8 { sse0: truncate_m128_to_m128i(self.sse0), sse1: truncate_m128_to_m128i(self.sse1) }
```

But since sse0/sse1 are private, I cannot do this. Is there an another way?

**Comment by Lokathor** [comment]
uh, you could change them to pub(crate) fields, that's simplest.

**Comment by RazrFalcon** [comment]
Ok, will do.
